### ISSUE TITLE
Bug: TypeError for Unexpected Keyword Argument 'proxy' in gotrue 2.9.1 with supabase-py 2.8.1

### ISSUE THREAD

**Issue by sivasai9849** [supabase/supabase-py#949]
## Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

I'm encountering a `TypeError` while using `supabase-py 2.8.1` in combination with `gotrue 2.9.1`. The error message is as follows:

```
TypeError: Client.__init__() got an unexpected keyword argument 'proxy'
```

This occurs when trying to create a Supabase client using the `create_client` method. It seems to be related to a change introduced in `gotrue 2.9.1`.

## To Reproduce

1. Install the following package versions:
   ```bash
   pip install gotrue==2.9.1
   pip install supabase==2.8.1
   ```
2. Attempt to create a Supabase client with the following code:
   ```python
   from supabase import create_client, Client
   
   url = SUPABASE_URL
   key = SUPABASE_SECRET
   supabase: Client = create_client(url, key)
   ```
3. The error `TypeError: Client.__init__() got an unexpected keyword argument 'proxy'` is raised.

## Expected behavior

The Supabase client should initialize successfully without raising a `TypeError`.

## Screenshots
![Screenshot of the error]<img width="1369" alt="Screenshot 2024-10-01 at 10 11 24 AM" src="https://github.com/user-attachments/assets/236dad3c-f1c8-4393-a52f-f766bbc585c4">

## System information

- **OS:** macOS
- **Version of supabase-py:** 2.8.1
- **Version of gotrue:** 2.9.1
- **Python version:** 3.10

## Additional context

The issue does not occur when downgrading to `gotrue 2.8.1`, so this appears to be a bug related to the latest release of `gotrue 2.9.1`.

**Comment by CalvinL15** [comment]
I can confirm that I am also facing the same issue, with Python 3.9. When using `supabase-py 2.8.1` in combination with `gotrue 2.8.1` and `httpx 0.25.1`, I faced `TypeError: __init__() got an unexpected keyword argument 'socket_options'` instead. `supabase-py 2.8.1` finally worked with httpx also downgraded to `0.24.1`.

**Comment by silentworks** [comment]
You need to upgrade your `httpx` to version `0.26` or a later version. This was a change added to `httpx`. We are going to release a new version of the library soon and set the minimal version to `0.26`.

**Comment by elitebyte** [comment]
Still hitting this issue with:

supabase==2.9.1
gotrue==2.9.3
httpx==0.27.2
uvicorn==0.32.0

**Comment by amansingh0311** [comment]
upgrade or downgrade to supabase==2.9.0 --> it will work

**Comment by elitebyte** [comment]
Tried these versions and still won't budge:

supabase==2.9.0
gotrue==2.9.3
httpx==0.24.1

**Comment by studentofcoding** [comment]
How to make it work on python 3.8

```
File "./main.py", line 80, in <module>
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/supabase/_sync/client.py", line 338, in create_client
    return SyncClient.create(
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/supabase/_sync/client.py", line 79, in __init__
    self.auth = self._init_supabase_auth_client(
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/supabase/_sync/client.py", line 250, in _init_supabase_auth_client
    return SyncSupabaseAuthClient(
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/supabase/_sync/auth_client.py", line 31, in __init__
    SyncGoTrueClient.__init__(
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/gotrue/_sync/gotrue_client.py", line 101, in __init__
    SyncGoTrueBaseAPI.__init__(
  File "/Users/gic_owner/miniforge3/lib/python3.8/site-packages/gotrue/_sync/gotrue_base_api.py", line 28, in __init__
    self._http_client = http_client or SyncClient(
TypeError: __init__() got an unexpected keyword argument 'proxy'
```

**Comment by kabirivan** [comment]
> upgrade httpx to a later version will work

It works !!! thanks

**Comment by faisald2926** [comment]
I faced a similar problem where I encountered a TypeError related to an unexpected 'proxy' argument when using gotrue 2.9.1 and supabase-py 2.8.1. This error occurred due to an incompatibility between the versions of the libraries, specifically with how the httpx client was being initialized. To fix it, I

Pinned httpx to >=0.24,<0.26 (compatible with Supabase).

Updated to the latest versions of supabase-py (2.8.2) and gotrue (2.9.2).

Cleared the build cache and redeployed.

It was a version mismatch issue, for me everything is working smoothly _for now_
